"""Independent scanner core for the Email Discovery SaaS."""

from email_scanner.batch_orchestration import BatchScanOrchestrator
from email_scanner.discovery import HTMLLinkExtractor, discover_and_rank_links
from email_scanner.dns import AsyncDNSResolver, SystemDNSResolver
from email_scanner.email_extraction import HTMLEmailExtractor
from email_scanner.email_pipeline import (
    calculate_domain_affinity,
    classify_email_category,
    extract_emails,
)
from email_scanner.email_validation import validate_email_candidate
from email_scanner.errors import (
    BatchItemOutcome,
    BatchScanConfigError,
    BatchScanConfigErrorCode,
    BatchScanOutcome,
    DelaySource,
    DiscoveryConfigError,
    DiscoveryConfigErrorCode,
    DiscoveryOutcomeCode,
    EmailRejectionCode,
    ExtractionConfigError,
    ExtractionConfigErrorCode,
    ExtractionOutcomeCode,
    FetchConfigError,
    FetchConfigErrorCode,
    FetchOutcomeCode,
    HostSafetyError,
    HostSafetyErrorCode,
    PageScanOutcome,
    RetryPolicyError,
    RetryPolicyErrorCode,
    RetryReason,
    RobotsDecisionCode,
    SiteScanConfigError,
    SiteScanConfigErrorCode,
    SiteScanOutcome,
    URLNormalizationError,
    URLNormalizationErrorCode,
)
from email_scanner.fetching import AsyncHTTPFetcher
from email_scanner.host_safety import validate_public_host
from email_scanner.models import (
    BatchScanConfig,
    BatchScanItem,
    BatchScanResult,
    BatchScanStatistics,
    CrawlScopeMode,
    DiscoveredLink,
    DiscoveryConfig,
    DiscoveryResult,
    DomainAffinity,
    EmailCategory,
    EmailDisposition,
    EmailEvidenceRecord,
    EmailExtractionConfig,
    EmailExtractionResult,
    EmailFinding,
    EmailSourceKind,
    FetchAttempt,
    FetchConfig,
    FetchResult,
    HostType,
    IPConnectionAttempt,
    NormalizedURL,
    PageScanRecord,
    PinningConfig,
    RankedPage,
    RedirectHop,
    RejectedEmailCandidate,
    RetryPolicy,
    RobotsDecision,
    SiteScanConfig,
    SiteScanResult,
    SiteScanStatistics,
)
from email_scanner.normalization import normalize_url
from email_scanner.orchestration import SiteScanOrchestrator
from email_scanner.pinned_transport import (
    PinnedAsyncHTTPTransport,
    PinnedAsyncNetworkBackend,
    PinnedAsyncNetworkStream,
)
from email_scanner.primary_selection import (
    PRIMARY_EMAIL_SELECTION_VERSION,
    PrimaryEmailSelectionResult,
    PrimaryEmailSelectionSignal,
    select_primary_email,
)
from email_scanner.ranking import RANKING_VERSION, calculate_page_score, rank_pages
from email_scanner.request_gate import (
    DomainRequestGate,
    RequestGateProtocol,
    get_domain_key,
)
from email_scanner.retry import (
    calculate_backoff_delay,
    parse_retry_after_header,
    should_retry_fetch,
)
from email_scanner.robots import RobotsPolicyEvaluator
from email_scanner.scope import (
    is_asset_url,
    is_in_scope,
    is_same_origin,
    is_same_registrable_domain,
)

__all__ = [
    "PRIMARY_EMAIL_SELECTION_VERSION",
    "RANKING_VERSION",
    "AsyncDNSResolver",
    "AsyncHTTPFetcher",
    "BatchItemOutcome",
    "BatchScanConfig",
    "BatchScanConfigError",
    "BatchScanConfigErrorCode",
    "BatchScanItem",
    "BatchScanOrchestrator",
    "BatchScanOutcome",
    "BatchScanResult",
    "BatchScanStatistics",
    "CrawlScopeMode",
    "DelaySource",
    "DiscoveredLink",
    "DiscoveryConfig",
    "DiscoveryConfigError",
    "DiscoveryConfigErrorCode",
    "DiscoveryOutcomeCode",
    "DiscoveryResult",
    "DomainAffinity",
    "DomainRequestGate",
    "EmailCategory",
    "EmailDisposition",
    "EmailEvidenceRecord",
    "EmailExtractionConfig",
    "EmailExtractionResult",
    "EmailFinding",
    "EmailRejectionCode",
    "EmailSourceKind",
    "ExtractionConfigError",
    "ExtractionConfigErrorCode",
    "ExtractionOutcomeCode",
    "FetchAttempt",
    "FetchConfig",
    "FetchConfigError",
    "FetchConfigErrorCode",
    "FetchOutcomeCode",
    "FetchResult",
    "HTMLEmailExtractor",
    "HTMLLinkExtractor",
    "HostSafetyError",
    "HostSafetyErrorCode",
    "HostType",
    "IPConnectionAttempt",
    "NormalizedURL",
    "PageScanOutcome",
    "PageScanRecord",
    "PinnedAsyncHTTPTransport",
    "PinnedAsyncNetworkBackend",
    "PinnedAsyncNetworkStream",
    "PinningConfig",
    "PrimaryEmailSelectionResult",
    "PrimaryEmailSelectionSignal",
    "RankedPage",
    "RedirectHop",
    "RejectedEmailCandidate",
    "RequestGateProtocol",
    "RetryPolicy",
    "RetryPolicyError",
    "RetryPolicyErrorCode",
    "RetryReason",
    "RobotsDecision",
    "RobotsDecisionCode",
    "RobotsPolicyEvaluator",
    "SiteScanConfig",
    "SiteScanConfigError",
    "SiteScanConfigErrorCode",
    "SiteScanOrchestrator",
    "SiteScanOutcome",
    "SiteScanResult",
    "SiteScanStatistics",
    "SystemDNSResolver",
    "URLNormalizationError",
    "URLNormalizationErrorCode",
    "calculate_backoff_delay",
    "calculate_domain_affinity",
    "calculate_page_score",
    "classify_email_category",
    "discover_and_rank_links",
    "extract_emails",
    "get_domain_key",
    "is_asset_url",
    "is_in_scope",
    "is_same_origin",
    "is_same_registrable_domain",
    "normalize_url",
    "parse_retry_after_header",
    "rank_pages",
    "select_primary_email",
    "should_retry_fetch",
    "validate_email_candidate",
    "validate_public_host",
]
