"""Independent scanner core for the Email Discovery SaaS."""

from email_scanner.discovery import HTMLLinkExtractor, discover_and_rank_links
from email_scanner.dns import AsyncDNSResolver, SystemDNSResolver
from email_scanner.email_extraction import HTMLEmailExtractor
from email_scanner.email_pipeline import (
    calculate_domain_affinity,
    classify_email_category,
    extract_emails,
)
from email_scanner.email_validation import validate_email_candidate
from email_scanner.errors import (
    DiscoveryConfigError,
    DiscoveryConfigErrorCode,
    DiscoveryOutcomeCode,
    EmailRejectionCode,
    ExtractionConfigError,
    ExtractionConfigErrorCode,
    ExtractionOutcomeCode,
    FetchConfigError,
    FetchConfigErrorCode,
    FetchOutcomeCode,
    HostSafetyError,
    HostSafetyErrorCode,
    PageScanOutcome,
    RobotsDecisionCode,
    SiteScanConfigError,
    SiteScanConfigErrorCode,
    SiteScanOutcome,
    URLNormalizationError,
    URLNormalizationErrorCode,
)
from email_scanner.fetching import AsyncHTTPFetcher
from email_scanner.host_safety import validate_public_host
from email_scanner.models import (
    CrawlScopeMode,
    DiscoveredLink,
    DiscoveryConfig,
    DiscoveryResult,
    DomainAffinity,
    EmailCategory,
    EmailDisposition,
    EmailExtractionConfig,
    EmailExtractionResult,
    EmailFinding,
    EmailSourceKind,
    FetchConfig,
    FetchResult,
    HostType,
    NormalizedURL,
    PageScanRecord,
    RankedPage,
    RedirectHop,
    RejectedEmailCandidate,
    RobotsDecision,
    SiteScanConfig,
    SiteScanResult,
    SiteScanStatistics,
)
from email_scanner.normalization import normalize_url
from email_scanner.orchestration import SiteScanOrchestrator
from email_scanner.ranking import RANKING_VERSION, calculate_page_score, rank_pages
from email_scanner.robots import RobotsPolicyEvaluator
from email_scanner.scope import (
    is_asset_url,
    is_in_scope,
    is_same_origin,
    is_same_registrable_domain,
)

__all__ = [
    "RANKING_VERSION",
    "AsyncDNSResolver",
    "AsyncHTTPFetcher",
    "CrawlScopeMode",
    "DiscoveredLink",
    "DiscoveryConfig",
    "DiscoveryConfigError",
    "DiscoveryConfigErrorCode",
    "DiscoveryOutcomeCode",
    "DiscoveryResult",
    "DomainAffinity",
    "EmailCategory",
    "EmailDisposition",
    "EmailExtractionConfig",
    "EmailExtractionResult",
    "EmailFinding",
    "EmailRejectionCode",
    "EmailSourceKind",
    "ExtractionConfigError",
    "ExtractionConfigErrorCode",
    "ExtractionOutcomeCode",
    "FetchConfig",
    "FetchConfigError",
    "FetchConfigErrorCode",
    "FetchOutcomeCode",
    "FetchResult",
    "HTMLEmailExtractor",
    "HTMLLinkExtractor",
    "HostSafetyError",
    "HostSafetyErrorCode",
    "HostType",
    "NormalizedURL",
    "PageScanOutcome",
    "PageScanRecord",
    "RankedPage",
    "RedirectHop",
    "RejectedEmailCandidate",
    "RobotsDecision",
    "RobotsDecisionCode",
    "RobotsPolicyEvaluator",
    "SiteScanConfig",
    "SiteScanConfigError",
    "SiteScanConfigErrorCode",
    "SiteScanOrchestrator",
    "SiteScanOutcome",
    "SiteScanResult",
    "SiteScanStatistics",
    "SystemDNSResolver",
    "URLNormalizationError",
    "URLNormalizationErrorCode",
    "calculate_domain_affinity",
    "calculate_page_score",
    "classify_email_category",
    "discover_and_rank_links",
    "extract_emails",
    "is_asset_url",
    "is_in_scope",
    "is_same_origin",
    "is_same_registrable_domain",
    "normalize_url",
    "rank_pages",
    "validate_email_candidate",
    "validate_public_host",
]
